before_script:
  - docker info

build-image:
  script:
    - docker build --pull=true -t concrete-python .
    - docker run concrete-python python setup.py test --addopts '--cov=concrete/ tests'
    - docker run concrete-python bash check-style.bash
    - docker run concrete-python python setup.py install --user test --addopts integration-tests
  tags:
    - shell
