test:anaconda:
  image: continuumio/anaconda
  script:
    - bash docker/anaconda-install-deps.bash
    - python setup.py test --addopts '--cov=concrete/ tests'
    - flake8 concrete/util

test:centos:
  image: centos:centos7
  script:
    - bash docker/centos-install-deps.bash
    - python setup.py test --addopts '--cov=concrete/ tests'
    - flake8 concrete/util

tox:centos:
  image: centos:centos7
  script:
    - bash docker/centos-install-deps.bash
    - tox

install:anaconda:
  image: continuumio/anaconda
  script:
    - bash docker/anaconda-install-deps.bash
    - python setup.py install

install:centos:
  image: centos:centos7
  script:
    - bash docker/centos-install-deps.bash
    - python setup.py install

