before_script:
  - docker info

build-test-ubuntu-accel:
  script:
    - docker build -t concrete-python-ubuntu:accel -f ubuntu.Dockerfile .
    - docker run concrete-python-ubuntu:accel bash check-style.bash
    - docker run concrete-python-ubuntu:accel python setup.py test
    - docker run concrete-python-ubuntu:accel python setup.py test --addopts integration-tests
  tags:
    - shell

build-test-deploy-accel:
  script:
    - docker build -t concrete-python:accel .
    - docker run concrete-python:accel bash check-style.bash
    - docker run concrete-python:accel python setup.py test
    - docker run concrete-python:accel python setup.py test --addopts integration-tests
    - docker tag concrete-python:accel r8n01:5000/concrete-python:accel
    - docker push r8n01:5000/concrete-python:accel
    - # work around gitlab CI... only deploy on master
      bash -c "[[ $CI_BUILD_REF_NAME != master ]] ||
      (docker tag concrete-python:accel r8n01:5000/concrete-python:accel &&
      docker push r8n01:5000/concrete-python:accel)"
  tags:
    - shell
